### ISSUE TITLE
Crash opening SnoozeActivity on Marshmallow

### ISSUE THREAD

**Issue by federicoiosue** [federicoiosue/Omni-Notes#222]
11-09 17:59:55.214 28892-28892/it.feio.android.omninotes E/AndroidRuntime: FATAL EXCEPTION: main
                                                                           Process: it.feio.android.omninotes, PID: 28892
                                                                           java.lang.RuntimeException: Unable to resume activity {it.feio.android.omninotes/it.feio.android.omninotes.SnoozeActivity}: java.lang.IllegalStateException: Activity {it.feio.android.omninotes/it.feio.android.omninotes.SnoozeActivity} did not call finish() prior to onResume() completing
                                                                               at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3103)
                                                                               at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3134)
                                                                               at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2481)
                                                                               at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
                                                                               at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                               at android.os.Looper.loop(Looper.java:148)
                                                                               at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                               at java.lang.reflect.Method.invoke(Native Method)
                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                                            Caused by: java.lang.IllegalStateException: Activity {it.feio.android.omninotes/it.feio.android.omninotes.SnoozeActivity} did not call finish() prior to onResume() completing
                                                                               at android.app.Activity.performResume(Activity.java:6324)
                                                                               at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3092)
                                                                               at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3134) 
                                                                               at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2481) 
                                                                               at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
                                                                               at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                               at android.os.Looper.loop(Looper.java:148) 
                                                                               at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                                               at java.lang.reflect.Method.invoke(Native Method) 
                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by federicoiosue** [comment]
Could be due to https://code.google.com/p/android-developer-preview/issues/detail?id=2353
