### ISSUE TITLE
Crash on new category creation

### ISSUE THREAD

**Issue by federicoiosue** [federicoiosue/Omni-Notes#226]
```
java.lang.ArrayIndexOutOfBoundsException: length=19; index=19
	at it.feio.android.omninotes.CategoryActivity.getRandomPaletteColor(CategoryActivity.java:84)
	at it.feio.android.omninotes.CategoryActivity.onCreate(CategoryActivity.java:73)
	at android.app.Activity.performCreate(Activity.java:5285)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1090)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2259)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2345)
	at android.app.ActivityThread.access$1100(ActivityThread.java:139)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:136)
	at android.app.ActivityThread.main(ActivityThread.java:5314)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:864)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:680)
	at dalvik.system.NativeStart.main(Native Method)
```

**Comment by federicoiosue** [comment]
It's due to wrong random category color definition
