### ISSUE TITLE
Android N - Click on reminder

### ISSUE THREAD

**Issue by federicoiosue** [federicoiosue/Omni-Notes#289]
```
E/Omni Notes: Error on receiving reminder
              java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String it.feio.android.omninotes.commons.models.Note.getContent()' on a null object reference
                  at it.feio.android.omninotes.utils.TextHelper.parseTitleAndContent(TextHelper.java:52)
                  at it.feio.android.omninotes.receiver.AlarmReceiver.createNotification(AlarmReceiver.java:62)
                  at it.feio.android.omninotes.receiver.AlarmReceiver.onReceive(AlarmReceiver.java:45)
                  at android.app.ActivityThread.handleReceiver(ActivityThread.java:2996)
                  at android.app.ActivityThread.-wrap18(ActivityThread.java)
                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1529)
                  at android.os.Handler.dispatchMessage(Handler.java:102)
                  at android.os.Looper.loop(Looper.java:154)
                  at android.app.ActivityThread.main(ActivityThread.java:6044)
                  at java.lang.reflect.Method.invoke(Native Method)
                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
```

**Comment by FredJul** [comment]
Android N does not support to give Parcelable into a PendingIntent anymore. I guess you should put the ID only and then retrieve the object thanks to that ID.
