### ISSUE TITLE
Error during notes trashing (beta)

### ISSUE THREAD

**Issue by federicoiosue** [federicoiosue/Omni-Notes#310]
To reproduce:

1. Fresh start the app
2. Select multiple notes
3. Trash them
4. Commit the action

12-18 14:43:33.906 E/ACRA    (14740): ACRA caught a IllegalStateException for it.feio.android.omninotes
12-18 14:43:33.906 E/ACRA    (14740): java.lang.IllegalStateException: Cannot perform this operation because the connection pool has been closed.
12-18 14:43:33.906 E/ACRA    (14740): 	at android.database.sqlite.SQLiteConnectionPool.throwIfClosedLocked(SQLiteConnectionPool.java:962)
12-18 14:43:33.906 E/ACRA    (14740): 	at android.database.sqlite.SQLiteConnectionPool.waitForConnection(SQLiteConnectionPool.java:599)
12-18 14:43:33.906 E/ACRA    (14740): 	at android.database.sqlite.SQLiteConnectionPool.acquireConnection(SQLiteConnectionPool.java:348)
12-18 14:43:33.906 E/ACRA    (14740): 	at android.database.sqlite.SQLiteSession.acquireConnection(SQLiteSession.java:894)
12-18 14:43:33.906 E/ACRA    (14740): 	at android.database.sqlite.SQLiteSession.executeForCursorWindow(SQLiteSession.java:834)
12-18 14:43:33.906 E/ACRA    (14740): 	at android.database.sqlite.SQLiteQuery.fillWindow(SQLiteQuery.java:62)
12-18 14:43:33.906 E/ACRA    (14740): 	at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:143)
12-18 14:43:33.906 E/ACRA    (14740): 	at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:132)
12-18 14:43:33.906 E/ACRA    (14740): 	at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:219)
12-18 14:43:33.906 E/ACRA    (14740): 	at android.database.AbstractCursor.moveToFirst(AbstractCursor.java:258)
12-18 14:43:33.906 E/ACRA    (14740): 	at it.feio.android.omninotes.db.DbHelper.getNotes(DbHelper.java:476)
12-18 14:43:33.906 E/ACRA    (14740): 	at it.feio.android.omninotes.db.DbHelper.getNotesActive(DbHelper.java:348)
12-18 14:43:33.906 E/ACRA    (14740): 	at it.feio.android.omninotes.extensions.ONDashClockExtension.getNotesCounters(ONDashClockExtension.java:115)
12-18 14:43:33.906 E/ACRA    (14740): 	at it.feio.android.omninotes.extensions.ONDashClockExtension.onUpdateData(ONDashClockExtension.java:63)
12-18 14:43:33.906 E/ACRA    (14740): 	at it.feio.android.omninotes.extensions.ONDashClockExtension$DashClockUpdateReceiver.onReceive(ONDashClockExtension.java:139)
12-18 14:43:33.906 E/ACRA    (14740): 	at android.support.v4.content.LocalBroadcastManager.executePendingBroadcasts(LocalBroadcastManager.java:297)
12-18 14:43:33.906 E/ACRA    (14740): 	at android.support.v4.content.LocalBroadcastManager.access$000(LocalBroadcastManager.java:46)
12-18 14:43:33.906 E/ACRA    (14740): 	at android.support.v4.content.LocalBroadcastManager$1.handleMessage(LocalBroadcastManager.java:116)
12-18 14:43:33.906 E/ACRA    (14740): 	at android.os.Handler.dispatchMessage(Handler.java:102)
12-18 14:43:33.906 E/ACRA    (14740): 	at android.os.Looper.loop(Looper.java:154)
12-18 14:43:33.906 E/ACRA    (14740): 	at android.app.ActivityThread.main(ActivityThread.java:6169)
12-18 14:43:33.906 E/ACRA    (14740): 	at java.lang.reflect.Method.invoke(Native Method)
12-18 14:43:33.906 E/ACRA    (14740): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888)
12-18 14:43:33.906 E/ACRA    (14740): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:778)
12-18 14:43:34.015 E/ACRA    (14740): Not adding buildConfig to log. Class Not found : it.feio.android.omninotes.BuildConfig. Please configure 'buildConfigClass' in your ACRA config
12-18 14:43:34.064 I/ActivityManager(918): Start proc 1898:it.feio.android.omninotes:acra/u0a284 for service it.feio.android.omninotes/org.acra.sender.SenderService
12-18 14:43:34.155 I/ACRA    (1898): Sending report /data/user/0/it.feio.android.omninotes/app_ACRA-approved/2016-12-18T14:43:33.973+01:00.stacktrace
12-18 14:43:36.649 I/ACRA    (1898): Request received by server
12-18 14:43:37.141 I/ACRA    (1966): ACRA is enabled for it.feio.android.omninotes, initializing...

**Comment by federicoiosue** [comment]
Outdated
