### ISSUE TITLE
Bulk operation fails

### ISSUE THREAD

**Issue by federicoiosue** [federicoiosue/Omni-Notes#337]
Steps to reproduce:
- Go into a category
- Select ALL the notes within
- Archive them
- Perform a commit

CRASH

**Comment by federicoiosue** [comment]
```
03-06 23:33:31.160 E/ACRA    (3311): ACRA caught a IllegalStateException for it.feio.android.omninotes
03-06 23:33:31.160 E/ACRA    (3311): java.lang.IllegalStateException: Cannot perform this operation because the connection pool has been closed.
03-06 23:33:31.160 E/ACRA    (3311): 	at android.database.sqlite.SQLiteConnectionPool.throwIfClosedLocked(SQLiteConnectionPool.java:962)
03-06 23:33:31.160 E/ACRA    (3311): 	at android.database.sqlite.SQLiteConnectionPool.waitForConnection(SQLiteConnectionPool.java:599)
03-06 23:33:31.160 E/ACRA    (3311): 	at android.database.sqlite.SQLiteConnectionPool.acquireConnection(SQLiteConnectionPool.java:348)
03-06 23:33:31.160 E/ACRA    (3311): 	at android.database.sqlite.SQLiteSession.acquireConnection(SQLiteSession.java:894)
03-06 23:33:31.160 E/ACRA    (3311): 	at android.database.sqlite.SQLiteSession.executeForCursorWindow(SQLiteSession.java:834)
03-06 23:33:31.160 E/ACRA    (3311): 	at android.database.sqlite.SQLiteQuery.fillWindow(SQLiteQuery.java:62)
03-06 23:33:31.160 E/ACRA    (3311): 	at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:143)
03-06 23:33:31.160 E/ACRA    (3311): 	at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:132)
03-06 23:33:31.160 E/ACRA    (3311): 	at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:219)
03-06 23:33:31.160 E/ACRA    (3311): 	at android.database.AbstractCursor.moveToFirst(AbstractCursor.java:258)
03-06 23:33:31.160 E/ACRA    (3311): 	at it.feio.android.omninotes.db.DbHelper.getNotes(DbHelper.java:476)
03-06 23:33:31.160 E/ACRA    (3311): 	at it.feio.android.omninotes.db.DbHelper.getNotesActive(DbHelper.java:348)
03-06 23:33:31.160 E/ACRA    (3311): 	at it.feio.android.omninotes.extensions.ONDashClockExtension.getNotesCounters(ONDashClockExtension.java:115)
03-06 23:33:31.160 E/ACRA    (3311): 	at it.feio.android.omninotes.extensions.ONDashClockExtension.onUpdateData(ONDashClockExtension.java:63)
03-06 23:33:31.160 E/ACRA    (3311): 	at it.feio.android.omninotes.extensions.ONDashClockExtension$DashClockUpdateReceiver.onReceive(ONDashClockExtension.java:139)
03-06 23:33:31.160 E/ACRA    (3311): 	at android.support.v4.content.LocalBroadcastManager.executePendingBroadcasts(LocalBroadcastManager.java:297)
03-06 23:33:31.160 E/ACRA    (3311): 	at android.support.v4.content.LocalBroadcastManager.access$000(LocalBroadcastManager.java:46)
03-06 23:33:31.160 E/ACRA    (3311): 	at android.support.v4.content.LocalBroadcastManager$1.handleMessage(LocalBroadcastManager.java:116)
03-06 23:33:31.160 E/ACRA    (3311): 	at android.os.Handler.dispatchMessage(Handler.java:102)
03-06 23:33:31.160 E/ACRA    (3311): 	at android.os.Looper.loop(Looper.java:154)
03-06 23:33:31.160 E/ACRA    (3311): 	at android.app.ActivityThread.main(ActivityThread.java:6169)
03-06 23:33:31.160 E/ACRA    (3311): 	at java.lang.reflect.Method.invoke(Native Method)
03-06 23:33:31.160 E/ACRA    (3311): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888)
03-06 23:33:31.160 E/ACRA    (3311): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:778)
03-06 23:33:31.376 E/ACRA    (3311): Not adding buildConfig to log. Class Not found : it.feio.android.omninotes.BuildConfig. Please configure 'buildConfigClass' in your ACRA config
```

**Comment by klawdhfzasjhaa** [comment]
In 5.3.2 from F-Droid this error does not come up. Also "Move to recycle bin" throws no error. But: "Archive" is still available also, when the notes are already archived.

**Comment by federicoiosue** [comment]
Thanks for reporting @klawdhfzasjhaa I supposed that too.

Current Beta flavor performs automatic backups of database data with JSONs on the filesystem. That's what could cause the issue.
