### ISSUE TITLE
5.3.1 crashes after update

### ISSUE THREAD

**Issue by Rbagman** [federicoiosue/Omni-Notes#342]
[Android 4.4.2] 5.3.1 crashes after update. Tried to roll it back but version are incompatible. Note folder is empty.

java.lang.RuntimeException: Unable to start activity ComponentInfo{it.feio.android.omninotes.foss/it.feio.android.omninotes.MainActivity}: java.lang.NullPointerException
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2413)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2471)
	at android.app.ActivityThread.access$900(ActivityThread.java:175)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1308)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:146)
	at android.app.ActivityThread.main(ActivityThread.java:5602)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.NullPointerException
	at it.feio.android.omninotes.BaseFragment.onStart(BaseFragment.java:13)
	at it.feio.android.omninotes.ListFragment.onStart(ListFragment.java:150)
	at android.support.v4.app.Fragment.performStart(Fragment.java:2000)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1102)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1252)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1234)
	at android.support.v4.app.FragmentManagerImpl.dispatchStart(FragmentManager.java:2051)
	at android.support.v4.app.FragmentController.dispatchStart(FragmentController.java:185)
	at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:608)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1177)
	at android.app.Activity.performStart(Activity.java:5461)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2386)
	... 12 more

**Comment by pneumatig** [comment]
Same problem here. I don't know why it crashed, and what exactly happend but I lost all my notes after upgrade to 5.3.1 via f-droid. Nightmare!!!

**Comment by federicoiosue** [comment]
https://github.com/federicoiosue/Omni-Notes/issues/336
