### ISSUE TITLE
Error on application start in Analitica library

### ISSUE THREAD

**Issue by Masterfans** [federicoiosue/Omni-Notes#343]
I just clone this project, not changed every file, but I just in Android studio click run application button, hint toast error : logcat message
it.feio.android.analitica.exceptions.InvalidIdentifierException: Piwik identifiers MUST be both service URL AND applicationId
     at it.feio.android.analitica.PiwikServiceIdentifier.validate(PiwikServiceIdentifier.java:23)
     at it.feio.android.analitica.ServiceIdentifier.<init>(ServiceIdentifier.java:14)
     at it.feio.android.analitica.PiwikServiceIdentifier.<init>(PiwikServiceIdentifier.java:14)
     at it.feio.android.analitica.AnalyticsHelperFactory.getAnalyticsHelper(AnalyticsHelperFactory.java:13)
     at it.feio.android.omninotes.OmniNotes.getAnalyticsHelper(OmniNotes.java:170)
     at it.feio.android.omninotes.BaseFragment.onStart(BaseFragment.java:13)
     at it.feio.android.omninotes.ListFragment.onStart(ListFragment.java:152)
     at android.support.v4.app.Fragment.performStart(Fragment.java:2000)
     at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1102)
     at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1252)
     at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1234)
     at android.support.v4.app.FragmentManagerImpl.dispatchStart(FragmentManager.java:2051)
     at android.support.v4.app.FragmentController.dispatchStart(FragmentController.java:185)
     at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:607)
     at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1328)
     at android.app.Activity.performStart(Activity.java:6050)
     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2387)
     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2486)
     at android.app.ActivityThread.access$800(ActivityThread.java:164)
     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1358)
     at android.os.Handler.dispatchMessage(Handler.java:102)
     at android.os.Looper.loop(Looper.java:147)
     at android.app.ActivityThread.main(ActivityThread.java:5513)
     at java.lang.reflect.Method.invoke(Native Method)
     at java.lang.reflect.Method.invoke(Method.java:372)
     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:971)
     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:766)
at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:133)

I don't konw how to solve, help me! thank you!

**Comment by federicoiosue** [comment]
The stacktrace is quite clear: you missed some parameters on AnalyticsHelper object initialization.

Give a look here for more informations: https://github.com/federicoiosue/analitica

**Comment by federicoiosue** [comment]
Did you find a fix @Masterfans ?

**Comment by Masterfans** [comment]
Thank you! I update /omniNotes/build.gradle file, again running is succeed, Thank you !!!

**Comment by Masterfans** [comment]
I see your are changed title to  Error on application start in Analitica library and add Development-Forks label. I thank may be an error in the library ,and then update the buidl.gradle, Thank you!

**Comment by federicoiosue** [comment]
Glad it worked @Masterfans
