### ISSUE TITLE
app crash on saving new note

### ISSUE THREAD

**Issue by rudinesurya** [federicoiosue/Omni-Notes#393]
i had previously downloaded omninote from google playstore and without removing it, i build another apk from the source into my phone. The apk generated does not replace the app, instead i now have 2 seperate copy of the omninote on my phone. the playstore copy still works fine, but the new one i build from android studio keeps crashing on adding new note. I guess it has something to do with database conflict. Deleting both the apps and installing from the android studio again does not resolve this problem.

**Comment by federicoiosue** [comment]
Hi, obviously there is something wrong with paths.

Omni Notes uses different paths for saving both internal and external (backups, attachments) depending on the build flavor.
For sure having a stacktrace would help to dig into the problem!

**Comment by rudinesurya** [comment]
Hi, thanks for the heads up. the reason of the crashing is due to the DateUtils class trying to parse a null value to long. 

here is the stack trace

11-04 14:04:23.141 1225-1295/it.feio.android.omninotes.foss E/ACRA: ACRA caught a RuntimeException for it.feio.android.omninotes.foss
                                                                    java.lang.RuntimeException: An error occurred while executing doInBackground()
                                                                        at android.os.AsyncTask$3.done(AsyncTask.java:318)
                                                                        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
                                                                        at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
                                                                        at java.util.concurrent.FutureTask.run(FutureTask.java:242)
                                                                        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                        at java.lang.Thread.run(Thread.java:761)
                                                                     Caused by: java.lang.NumberFormatException: null
                                                                        at java.lang.Long.parseLong(Long.java:406)
                                                                        at java.lang.Long.parseLong(Long.java:485)
                                                                        at it.feio.android.omninotes.utils.date.DateUtils.isFuture(DateUtils.java:175)
                                                                        at it.feio.android.omninotes.async.notes.SaveNoteTask.doInBackground(SaveNoteTask.java:60)
                                                                        at it.feio.android.omninotes.async.notes.SaveNoteTask.doInBackground(SaveNoteTask.java:36)
                                                                        at android.os.AsyncTask$2.call(AsyncTask.java:304)
                                                                        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
                                                                        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
                                                                        at java.lang.Thread.run(Thread.java:761) 
11-04 14:04:23.272 1225-1295/it.feio.android.omninotes.foss E/ACRA: Not adding buildConfig to log. Class Not found : it.feio.android.omninotes.foss.BuildConfig. Please configure 'buildConfigClass' in your ACRA config
11-04 14:04:25.232 1225-1456/it.feio.android.omninotes.foss I/Process: Sending signal. PID: 1225 SIG: 9

**Comment by federicoiosue** [comment]
Always keep your fork in sync with the develop branch
