### ISSUE TITLE
Crash on app re-opening

### ISSUE THREAD

**Issue by federicoiosue** [federicoiosue/Omni-Notes#398]
https://app.tracepot.com/app/1664/release/62e7225900000680

```
java.lang.RuntimeException: Unable to resume activity {it.feio.android.omninotes/it.feio.android.omninotes.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.Long.equals(java.lang.Object)' on a null object reference
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3572)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3612)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2825)
	at android.app.ActivityThread.-wrap12(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1532)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6321)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.Long.equals(java.lang.Object)' on a null object reference
	at it.feio.android.omninotes.MainActivity.noteAlreadyOpened(MainActivity.java:385)
	at it.feio.android.omninotes.MainActivity.handleIntents(MainActivity.java:326)
	at it.feio.android.omninotes.MainActivity.onNewIntent(MainActivity.java:159)
	at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1284)
	at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1301)
	at android.app.ActivityThread.deliverNewIntents(ActivityThread.java:2895)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3535)
	... 10 more
```

**Comment by federicoiosue** [comment]
Was already fixed in a previous beta version
