### ISSUE TITLE
NullPointerException when adding note from widget (not always)

### ISSUE THREAD

**Issue by federicoiosue** [federicoiosue/Omni-Notes#487]
```
Caused by: java.lang.NullPointerException
	at it.feio.android.omninotes.MainActivity.switchToDetail(MainActivity.java:420)
	at it.feio.android.omninotes.MainActivity.handleIntents(MainActivity.java:367)
	at it.feio.android.omninotes.MainActivity.onNewIntent(MainActivity.java:178)
````

**Comment by federicoiosue** [comment]
https://app.tracepot.com/app/1664/release/1d9eadb600000680?ftfield=logcat&ftvalue=&page=1&fbpage=1
