### ISSUE TITLE
Interrupted JSON-based backup 

### ISSUE THREAD

**Issue by federicoiosue** [federicoiosue/Omni-Notes#627]
```
FATAL EXCEPTION: IntentService[DataBackupIntentService]
Process: it.feio.android.omninotes.alpha, PID: 6155
java.lang.RuntimeException: Could not copy bitmap to parcel blob.
	at android.graphics.Bitmap.nativeWriteToParcel(Native Method)
	at android.graphics.Bitmap.writeToParcel(Bitmap.java:1821)
	at android.graphics.drawable.Icon.writeToParcel(Icon.java:773)
	at android.os.Parcel.writeParcelable(Parcel.java:1792)
	at android.os.Parcel.writeValue(Parcel.java:1698)
	at android.os.Parcel.writeArrayMapInternal(Parcel.java:838)
	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1542)
	at android.os.Bundle.writeToParcel(Bundle.java:1232)
	at android.os.Parcel.writeBundle(Parcel.java:878)
	at android.app.Notification.writeToParcelImpl(Notification.java:2372)
	at android.app.Notification.writeToParcel(Notification.java:2265)
	at android.app.INotificationManager$Stub$Proxy.enqueueNotificationWithTag(INotificationManager.java:1439)
	at android.app.NotificationManager.notifyAsUser(NotificationManager.java:320)
	at android.app.NotificationManager.notify(NotificationManager.java:289)
	at android.app.NotificationManager.notify(NotificationManager.java:273)
	at it.feio.android.omninotes.utils.notifications.NotificationsHelper.updateMessage(NotificationsHelper.java:172)
	at it.feio.android.omninotes.utils.notifications.NotificationsHelper.updateMessage(NotificationsHelper.java:168)
	at it.feio.android.omninotes.async.DataBackupIntentService.exportAttachments(DataBackupIntentService.java:507)
	at it.feio.android.omninotes.async.DataBackupIntentService.exportData(DataBackupIntentService.java:136)
	at it.feio.android.omninotes.async.DataBackupIntentService.onHandleIntent(DataBackupIntentService.java:109)
	at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:76)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:164)
	at android.os.HandlerThread.run(HandlerThread.java:65)
```

**Comment by federicoiosue** [comment]
@11510746 I still didn't worked on that. I found by looking to my own device's logs. 
I think is related to bad/missing attachment to a note. What should be done in these cases should to continue process and logging problems. Eventually sending it to me.

**Comment by federicoiosue** [comment]
This could be useful to achieve that https://github.com/sschendel/RemoteLogger
