### ISSUE TITLE
BOOT_COMPLETED problem on Oreo

### ISSUE THREAD

**Issue by federicoiosue** [federicoiosue/Omni-Notes#652]
`java.lang.RuntimeException: Unable to start receiver it.feio.android.omninotes.receiver.BootCompleteReceiver: java.lang.IllegalStateException: Not allowed to start service Intent { cmp=it.feio.android.omninotes/.async.AlarmRestoreOnRebootService }: app is in background uid UidRecord{a3ea4fc u0a273 RCVR idle procs:1 seq(0,0,0)}`

**Comment by federicoiosue** [comment]
Full stacktrace

```
java.lang.RuntimeException: Unable to start receiver it.feio.android.omninotes.receiver.BootCompleteReceiver: java.lang.IllegalStateException: Not allowed to start service Intent { cmp=it.feio.android.omninotes/.async.AlarmRestoreOnRebootService }: app is in background uid UidRecord{bb5f87e u0a100 RCVR idle change:uncached procs:1 seq(0,0,0)}
	at android.app.ActivityThread.handleReceiver(ActivityThread.java:3426)
	at android.app.ActivityThread.access$1200(ActivityThread.java:200)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1667)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6718)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
Caused by: java.lang.IllegalStateException: Not allowed to start service Intent { cmp=it.feio.android.omninotes/.async.AlarmRestoreOnRebootService }: app is in background uid UidRecord{bb5f87e u0a100 RCVR idle change:uncached procs:1 seq(0,0,0)}
	at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1577)
	at android.app.ContextImpl.startService(ContextImpl.java:1532)
	at android.content.ContextWrapper.startService(ContextWrapper.java:664)
	at android.content.ContextWrapper.startService(ContextWrapper.java:664)
	at it.feio.android.omninotes.receiver.BootCompleteReceiver.onReceive(BootCompleteReceiver.java:35)
	at android.app.ActivityThread.handleReceiver(ActivityThread.java:3417)
	... 8 more
```
