### ISSUE TITLE
Db error

### ISSUE THREAD

**Issue by federicoiosue** [federicoiosue/Omni-Notes#668]
ACRA caught a IllegalStateException for it.feio.android.omninotes
java.lang.IllegalStateException: Cannot perform this operation because the connection pool has been closed.
	at android.database.sqlite.SQLiteConnectionPool.throwIfClosedLocked(SQLiteConnectionPool.java:1069)
	at android.database.sqlite.SQLiteConnectionPool.waitForConnection(SQLiteConnectionPool.java:683)
	at android.database.sqlite.SQLiteConnectionPool.acquireConnection(SQLiteConnectionPool.java:378)
	at android.database.sqlite.SQLiteSession.acquireConnection(SQLiteSession.java:894)
	at android.database.sqlite.SQLiteSession.executeForCursorWindow(SQLiteSession.java:834)
	at android.database.sqlite.SQLiteQuery.fillWindow(SQLiteQuery.java:62)
	at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:149)
	at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:137)
	at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:220)
	at android.database.AbstractCursor.moveToFirst(AbstractCursor.java:259)
	at it.feio.android.omninotes.db.DbHelper.getNotes(DbHelper.java:444)
	at it.feio.android.omninotes.widget.ListRemoteViewsFactory.onDataSetChanged(ListRemoteViewsFactory.java:96)
	at android.widget.RemoteViewsService$RemoteViewsFactoryAdapter.onDataSetChanged(RemoteViewsService.java:142)
	at com.android.internal.widget.IRemoteViewsFactory$Stub.onTransact(IRemoteViewsFactory.java:50)
	at android.os.Binder.execTransact(Binder.java:752)

**Comment by federicoiosue** [comment]
Didn't happened anymore
