### ISSUE TITLE
Build Failed when click Run, before and after gradle update.

### ISSUE THREAD

**Issue by BezMan** [federicoiosue/Omni-Notes#670]
Caused by: org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':omniNotes:processAlphaDebugResources'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:110)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:77)
	at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:59)
	at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:59)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:101)
	at org.gradle.api.internal.tasks.execution.FinalizeInputFilePropertiesTaskExecuter.execute(FinalizeInputFilePropertiesTaskExecuter.java:44)
	at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:91)
	at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:62)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:59)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.run(EventFiringTaskExecuter.java:51)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:300)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:292)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:174)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:46)
	at org.gradle.execution.taskgraph.LocalTaskInfoExecutor.execute(LocalTaskInfoExecutor.java:42)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareWorkItemExecutor.execute(DefaultTaskExecutionGraph.java:277)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareWorkItemExecutor.execute(DefaultTaskExecutionGraph.java:262)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:135)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:130)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.execute(DefaultTaskPlanExecutor.java:200)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.executeWithWork(DefaultTaskPlanExecutor.java:191)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.run(DefaultTaskPlanExecutor.java:130)
	... 6 more
Caused by: com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource linking failed
warn: removing resource it.feio.android.omninotes.alpha:array/preferences_default_reminder_labels without required default value.
warn: removing resource it.feio.android.omninotes.alpha:array/preferences_week_start_day_labels without required default value.
warn: removing resource it.feio.android.omninotes.alpha:string/deleted_key without required default value.
C:\Users\f.laurent\dev\perso\github\datetimepicker\datetimepicker-library\res\layout\date_picker_header_view.xml:2: AAPT: error: resource id/date_picker_header (aka it.feio.android.omninotes.alpha:id/date_picker_header) not found.
    
C:\Users\f.laurent\dev\perso\github\datetimepicker\datetimepicker-library\res\layout\date_picker_selected_date.xml:2: AAPT: error: resource id/day_picker_selected_date_layout (aka it.feio.android.omninotes.alpha:id/day_picker_selected_date_layout) not found.
    
C:\Users\f.laurent\dev\perso\github\datetimepicker\datetimepicker-library\res\layout\date_picker_selected_date.xml:4: AAPT: error: resource id/date_picker_month_and_day (aka it.feio.android.omninotes.alpha:id/date_picker_month_and_day) not found.
    
C:\Users\f.laurent\dev\perso\github\datetimepicker\datetimepicker-library\res\layout\date_picker_selected_date.xml:5: AAPT: error: resource id/date_picker_month (aka it.feio.android.omninotes.alpha:id/date_picker_month) not found.
    
C:\Users\f.laurent\dev\perso\github\datetimepicker\datetimepicker-library\res\layout\date_picker_selected_date.xml:6: AAPT: error: resource id/date_picker_day (aka it.feio.android.omninotes.alpha:id/date_picker_day) not found.
    
C:\Users\f.laurent\dev\perso\github\datetimepicker\datetimepicker-library\res\layout\date_picker_selected_date.xml:8: AAPT: error: resource id/date_picker_year (aka it.feio.android.omninotes.alpha:id/date_picker_year) not found.
    
C:\Users\f.laurent\dev\perso\github\datetimepicker\datetimepicker-library\res\layout\date_picker_view_animator.xml:2: AAPT: error: resource id/animator (aka it.feio.android.omninotes.alpha:id/animator) not found.
    
C:\Users\f.laurent\dev\perso\github\datetimepicker\datetimepicker-library\res\layout\year_label_text_view.xml:2: AAPT: error: resource id/month_text_view (aka it.feio.android.omninotes.alpha:id/month_text_view) not found.
    
error: failed linking file resources.
	at com.android.builder.internal.aapt.v2.Aapt2Exception$Companion.create(Aapt2Exception.kt:45)
	at com.android.builder.internal.aapt.v2.Aapt2Exception$Companion.create$default(Aapt2Exception.kt:39)
	at com.android.build.gradle.internal.res.Aapt2ErrorUtils.rewriteException(Aapt2ErrorUtils.kt:97)
	at com.android.build.gradle.internal.res.Aapt2ErrorUtils.rewriteLinkException(Aapt2ErrorUtils.kt:73)
	at com.android.build.gradle.internal.res.LinkApplicationAndroidResourcesTask.invokeAaptForSplit(LinkApplicationAndroidResourcesTask.java:515)
	at com.android.build.gradle.internal.res.LinkApplicationAndroidResourcesTask.doFullTaskAction(LinkApplicationAndroidResourcesTask.java:257)
	at com.android.build.gradle.internal.tasks.IncrementalTask.taskAction(IncrementalTask.java:106)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
	at org.gradle.api.internal.project.taskfactory.IncrementalTaskAction.doExecute(IncrementalTaskAction.java:50)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:39)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:26)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:131)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:300)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:292)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:174)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:120)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:99)
	... 34 more
Caused by: com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource linking failed
warn: removing resource it.feio.android.omninotes.alpha:array/preferences_default_reminder_labels without required default value.
warn: removing resource it.feio.android.omninotes.alpha:array/preferences_week_start_day_labels without required default value.
warn: removing resource it.feio.android.omninotes.alpha:string/deleted_key without required default value.
C:\Users\owner\.gradle\caches\transforms-1\files-1.1\library-0.0.2.aar\9fc829968be835ab9ca51317af249d33\res\layout\date_picker_header_view.xml:2: error: resource id/date_picker_header (aka it.feio.android.omninotes.alpha:id/date_picker_header) not found.
C:\Users\owner\.gradle\caches\transforms-1\files-1.1\library-0.0.2.aar\9fc829968be835ab9ca51317af249d33\res\layout\date_picker_selected_date.xml:2: error: resource id/day_picker_selected_date_layout (aka it.feio.android.omninotes.alpha:id/day_picker_selected_date_layout) not found.
C:\Users\owner\.gradle\caches\transforms-1\files-1.1\library-0.0.2.aar\9fc829968be835ab9ca51317af249d33\res\layout\date_picker_selected_date.xml:4: error: resource id/date_picker_month_and_day (aka it.feio.android.omninotes.alpha:id/date_picker_month_and_day) not found.
C:\Users\owner\.gradle\caches\transforms-1\files-1.1\library-0.0.2.aar\9fc829968be835ab9ca51317af249d33\res\layout\date_picker_selected_date.xml:5: error: resource id/date_picker_month (aka it.feio.android.omninotes.alpha:id/date_picker_month) not found.
C:\Users\owner\.gradle\caches\transforms-1\files-1.1\library-0.0.2.aar\9fc829968be835ab9ca51317af249d33\res\layout\date_picker_selected_date.xml:6: error: resource id/date_picker_day (aka it.feio.android.omninotes.alpha:id/date_picker_day) not found.
C:\Users\owner\.gradle\caches\transforms-1\files-1.1\library-0.0.2.aar\9fc829968be835ab9ca51317af249d33\res\layout\date_picker_selected_date.xml:8: error: resource id/date_picker_year (aka it.feio.android.omninotes.alpha:id/date_picker_year) not found.
C:\Users\owner\.gradle\caches\transforms-1\files-1.1\library-0.0.2.aar\9fc829968be835ab9ca51317af249d33\res\layout\date_picker_view_animator.xml:2: error: resource id/animator (aka it.feio.android.omninotes.alpha:id/animator) not found.
C:\Users\owner\.gradle\caches\transforms-1\files-1.1\library-0.0.2.aar\9fc829968be835ab9ca51317af249d33\res\layout\year_label_text_view.xml:2: error: resource id/month_text_view (aka it.feio.android.omninotes.alpha:id/month_text_view) not found.
error: failed linking file resources.

**Comment by federicoiosue** [comment]
Hi there, 

the issue should be fixed, now the builds on develop branch are [back to work](https://travis-ci.org/federicoiosue/Omni-Notes/builds/623261614?utm_medium=notification&utm_source=email)!
