### ISSUE TITLE
Beta 9 - Reminders stopped working

### ISSUE THREAD

**Issue by aabm197** [federicoiosue/Omni-Notes#673]
Omni Notes Version 6.0.0 Beta 9 Apr 18, 2019

Android version: 8.0.0

**After update to Beta 9, Reminder Notifications are not working at all.**

From Omni Notes log file (for a reminder set for 24 Apr 22:41):

04-24 22:41:00.504 28594-28594 E/Error on receiving reminder: android.os.BadParcelableException: ClassNotFoundException when unmarshalling: 
	at android.os.Parcel.readParcelableCreator(Parcel.java:2855)
	at android.os.Parcel.readParcelable(Parcel.java:2781)
	at it.feio.android.omninotes.models.Note.<init>(Note.java:84)
	at it.feio.android.omninotes.models.Note.<init>(Note.java:30)
	at it.feio.android.omninotes.models.Note$1.createFromParcel(Note.java:39)
	at it.feio.android.omninotes.models.Note$1.createFromParcel(Note.java:36)
	at it.feio.android.omninotes.utils.ParcelableUtil.unmarshall(ParcelableUtil.java:45)
	at it.feio.android.omninotes.receiver.AlarmReceiver.onReceive(AlarmReceiver.java:51)
	at android.app.ActivityThread.handleReceiver(ActivityThread.java:3357)
	at android.app.ActivityThread.-wrap17(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1755)
	at android.os.Handler.dispatchMessage(Handler.java:108)
	at android.os.Looper.loop(Looper.java:206)
	at android.app.ActivityThread.main(ActivityThread.java:6784)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:852)

Thanks and Regards

**Comment by federicoiosue** [comment]
Problem confirmed, I coded a test that checks for that problem to dig further into the solution avoiding regression errors. Thanks for reporting it!

**Comment by MadTomT** [comment]
Any idea when this will be resolved or do we need to roll back to a previous version ?

**Comment by mayis84** [comment]
And I have Android 10 in xiaomi mi A2 lite. The reminder does not working..

**Comment by mayis84** [comment]
Reminder does not working ....! Why did you closed this issue ? What I have to do for working my reminders ?

**Comment by federicoiosue** [comment]
I'm releasing right now the updated version on Play Store. The commit above refers to fixing code.

**Comment by mayis84** [comment]
Ok.. thanks .

**Comment by mayis84** [comment]
Sorry friend, the notification work's but no sound and vibration ...

**Comment by MadTomT** [comment]
Hi. I get sound and vibration, but not from the setting in the app. I have to go to system, applications and configure the notification settings for this app for it to work.

**Comment by aabm197** [comment]
This is just to confirm that the reminders are working again after update to Beta 10..
Thanks and Regards

**Comment by federicoiosue** [comment]
Great thanks!

**Comment by mayis84** [comment]
Sorry friends, I understand what do you mean, but I configured system notification app notification before. I get every notification from other app(sound and vibration) but not from Omni notes. Please help me.. I like this app. What do you think about Android version ? I have Android one version 10. Xiaomi mi A2 lite. Without MIUI

**Comment by mayis84** [comment]
Hello again 
I have trouble with notification.. as I mentioned earlier.  Notification works but sounds and vibration doesn't works.. I have updated soft to the last version. 
Please give assistance to me to resolve this problem. 
My phone Xiaomi Mi a2 lite. Android 9

**Comment by mayis84** [comment]
I have installed beta version...
