### ISSUE TITLE
Crash on recurrent reminder fired

### ISSUE THREAD

**Issue by federicoiosue** [federicoiosue/Omni-Notes#711]
Affecting version **6.0.0**

```
java.lang.NoClassDefFoundError: Failed resolution of: Lorg/apache/commons/logging/LogFactory;
	at net.fortuna.ical4j.util.Configurator.<clinit>(Configurator.java:51)
	at net.fortuna.ical4j.util.Configurator.getProperty(Configurator.java:75)
	at net.fortuna.ical4j.model.Recur.<clinit>(Recur.java:138)
	at net.fortuna.ical4j.model.property.RRule.<init>(RRule.java:61)
	at it.feio.android.omninotes.helpers.date.DateHelper.nextReminderFromRecurrenceRule(DateHelper.java:163)
	at it.feio.android.omninotes.helpers.date.DateHelper.nextReminderFromRecurrenceRule(DateHelper.java:158)
	at it.feio.android.omninotes.SnoozeActivity.setNextRecurrentReminder(SnoozeActivity.java:136)
	at it.feio.android.omninotes.receiver.AlarmReceiver.onReceive(AlarmReceiver.java:54)
	at android.app.ActivityThread.handleReceiver(ActivityThread.java:3602)
	at android.app.ActivityThread.access$1300(ActivityThread.java:236)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1795)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7037)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
Caused by: java.lang.ClassNotFoundException: Didn't find class "org.apache.commons.logging.LogFactory" on path: DexPathList[[zip file "/data/app/it.feio.android.omninotes-2bc2p0pCh6P2JNY_9NhK1A==/base.apk"],nativeLibraryDirectories=[/data/app/it.feio.android.omninotes-2bc2p0pCh6P2JNY_9NhK1A==/lib/arm64, /system/lib64]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	... 17 more
``
`

**Comment by federicoiosue** [comment]
[DateHelperTest](https://github.com/federicoiosue/Omni-Notes/blob/develop/omniNotes/src/test/java/it/feio/android/omninotes/utils/date/DateHelperTest.java) was **not** annotated to run so, even if a test was been provided to certificate a correct behavior **it was not runned!!!!**

Shame on me.
