### ISSUE TITLE
Unless the data is cleared, Omni-Notes cannot change the language according to the system settings

### ISSUE THREAD

**Issue by sjl872964789** [federicoiosue/Omni-Notes#775]
**Describe the bug**
Once the welcome interface is passed, Omni-Notes cannot change the language according to the system settings unless the data is cleared

**Context**
 - Device: [MI CC 9e]/[PIXEL XL]
 - OS version: [MIUI 10.2.10]/[Android 10.0]
 - App version: [6.0.5]

**How to reproduce**
1. Install Omni Notes and open
2. Skip all welcome screens
3. Change to another language in system settings (E.g. Chinese)
4. Back to Omni-Notes
5. Clear Omni-Notes from the background and reopen it
6. Unless the data is cleared, the language of Omni-Notes is always English

**Expected behavior**
Omni-Notes can be changed to the language in the system settings.

**Screenshots**
![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/15941953/90253856-6dec5980-de74-11ea-8c5d-2a446c15d74d.gif)

**Logcat**
```
08-19 16:03:58.440 17723 17723 E AndroidRuntime: FATAL EXCEPTION: main
08-19 16:03:58.440 17723 17723 E AndroidRuntime: Process: com.amaze.filemanager, PID: 17723
08-19 16:03:58.440 17723 17723 E AndroidRuntime: java.lang.RuntimeException: Failure delivering result ResultInfo{who=@android:requestPermissions:, request=0, result=-1, data=Intent { act=android.content.pm.action.REQUEST_PERMISSIONS (has extras) }} to activity {com.amaze.filemanager/com.amaze.filemanager.activities.MainActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'void com.amaze.filemanager.activities.superclasses.PermissionsActivity$OnPermissionGranted.onPermissionGranted()' on a null object reference
08-19 16:03:58.440 17723 17723 E AndroidRuntime:        at android.app.ActivityThread.deliverResults(ActivityThread.java:5052)
08-19 16:03:58.440 17723 17723 E AndroidRuntime:        at android.app.ActivityThread.handleSendResult(ActivityThread.java:5094)
08-19 16:03:58.440 17723 17723 E AndroidRuntime:        at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:49)
08-19 16:03:58.440 17723 17723 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:117)
08-19 16:03:58.440 17723 17723 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:74)
08-19 16:03:58.440 17723 17723 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2208)
08-19 16:03:58.440 17723 17723 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:112)
08-19 16:03:58.440 17723 17723 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:216)
08-19 16:03:58.440 17723 17723 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7579)
08-19 16:03:58.440 17723 17723 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
08-19 16:03:58.440 17723 17723 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
08-19 16:03:58.440 17723 17723 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)
08-19 16:03:58.440 17723 17723 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'void com.amaze.filemanager.activities.superclasses.PermissionsActivity$OnPermissionGranted.onPermissionGranted()' on a null object reference
08-19 16:03:58.440 17723 17723 E AndroidRuntime:        at com.amaze.filemanager.activities.superclasses.PermissionsActivity.onRequestPermissionsResult(PermissionsActivity.java:30)
08-19 16:03:58.440 17723 17723 E AndroidRuntime:        at android.app.Activity.dispatchRequestPermissionsResult(Activity.java:7999)
08-19 16:03:58.440 17723 17723 E AndroidRuntime:        at android.app.Activity.dispatchActivityResult(Activity.java:7849)
08-19 16:03:58.440 17723 17723 E AndroidRuntime:        at android.app.ActivityThread.deliverResults(ActivityThread.java:5045)
08-19 16:03:58.440 17723 17723 E AndroidRuntime:        ... 11 more
```

**Comment by sjl872964789** [comment]
Hi，any update about this issue？It would be really appreciated to get your concern on this.
