### ISSUE TITLE
Null

### ISSUE THREAD

**Issue by federicoiosue** [federicoiosue/Omni-Notes#811]
ACRA caught a NullPointerException for it.feio.android.omninotes.alpha
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.service.notification.StatusBarNotification.getPackageName()' on a null object reference
	at it.feio.android.omninotes.services.NotificationListener.onNotificationRemoved(NotificationListener.java:54)
	at android.service.notification.NotificationListenerService.onNotificationRemoved(NotificationListenerService.java:401)
	at android.service.notification.NotificationListenerService.onNotificationRemoved(NotificationListenerService.java:427)
	at android.service.notification.NotificationListenerService.onNotificationRemoved(NotificationListenerService.java:440)
	at android.service.notification.NotificationListenerService$MyHandler.handleMessage(NotificationListenerService.java:2110)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7697)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

**Comment by federicoiosue** [comment]
Should be fixed in 5a88b24a990367c9567b2a4a1aeece057d50fbc4
