### ISSUE TITLE
Find some crashes!

### ISSUE THREAD

**Issue by LvZW1895** [federicoiosue/Omni-Notes#821]
APK Version : 6.1.0 Alpha 1
AndroidOS Version = 7.0-9.0
**Description information：**
These crashes happened by accident when I was testing in different devices. I tried to reproduce them and found that they can't be reproduced, but they are real. I hope they can help you to debug.

**Crash1:**
Long Msg: android.content.ActivityNotFoundException: Unable to find explicit activity class {it.feio.android.omninotes.alpha/it.feio.android.omninotes.StatsActivity}; have you declared this activity in your AndroidManifest.xml?
	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1812)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1525)
	at android.app.Activity.startActivityForResult(Activity.java:4398)
	at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:675)
	at android.app.Activity.startActivityForResult(Activity.java:4356)
	at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:662)
	at android.app.Activity.startActivity(Activity.java:4695)
	at android.app.Activity.startActivity(Activity.java:4663)
	at androidx.preference.Preference.performClick(Preference.java:1199)
	at androidx.preference.Preference.performClick(Preference.java:1166)
	at androidx.preference.Preference$1.onClick(Preference.java:181)
	at android.view.View.performClick(View.java:5647)
	at android.view.View$PerformClick.run(View.java:22465)
	at android.os.Handler.handleCallback(Handler.java:754)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:163)
	at android.app.ActivityThread.main(ActivityThread.java:6395)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794)

**Crash2:**
Long Msg: java.lang.ArrayIndexOutOfBoundsException: length=2; index=-1
	at java.util.Arrays$ArrayList.get(Arrays.java:3854)
	at it.feio.android.omninotes.SettingsFragment.lambda$importNotes$28$SettingsFragment(SettingsFragment.java:589)
	at it.feio.android.omninotes.-$$Lambda$SettingsFragment$zIyqPhzasHgnx9FX4FxKeDwte4g.onClick(lambda)
	at androidx.appcompat.app.AlertController$ButtonHandler.handleMessage(AlertController.java:167)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:163)
	at android.app.ActivityThread.main(ActivityThread.java:6395)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794)

**Comment by federicoiosue** [comment]
Hi there, on which device does this happen? When you say "testing" you mean running unit/instrumentation tests or manual ones?

**Comment by LvZW1895** [comment]
device： MI 5X
We are developing a new automated testing tool, you can understand this as an advanced Monkey. We happen to test on Omni-Notes and found these two crashes. If you need further info, just let me know.

**Comment by sampath-houde** [comment]
is it been resolved?

**Comment by federicoiosue** [comment]
> is it been resolved?

Marked as non-replicable as I've not been able to reproduce it. Did you encountered this kind of error somewhere?

**Comment by federicoiosue** [comment]
Closed due to missing information and impossiblity of reproducing
