### ISSUE TITLE
Error sharing attachments

### ISSUE THREAD

**Issue by federicoiosue** [federicoiosue/Omni-Notes#903]
```
android.os.FileUriExposedException: file:///storage/emulated/0/Android/data/it.feio.android.omninotes.alpha/files/20230328_130658_028.jpg exposed beyond app through ClipData.Item.getUri()
	at android.os.StrictMode.onFileUriExposed(StrictMode.java:2208)
	at android.net.Uri.checkFileUriExposed(Uri.java:2407)
	at android.content.ClipData.prepareToLeaveProcess(ClipData.java:1052)
	at android.content.Intent.prepareToLeaveProcess(Intent.java:11824)
	at android.content.Intent.prepareToLeaveProcess(Intent.java:11833)
	at android.content.Intent.prepareToLeaveProcess(Intent.java:11809)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1800)
	at android.app.Activity.startActivityForResult(Activity.java:5470)
	at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:675)
	at android.app.Activity.startActivityForResult(Activity.java:5428)
	at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:662)
	at android.app.Activity.startActivity(Activity.java:5926)
	at android.app.Activity.startActivity(Activity.java:5893)
	at it.feio.android.omninotes.MainActivity.shareNote(MainActivity.java:532)
	at it.feio.android.omninotes.DetailFragment.shareNote(DetailFragment.java:1640)
	at it.feio.android.omninotes.DetailFragment.onOptionsItemSelected(DetailFragment.java:1057)
	at androidx.fragment.app.Fragment.performOptionsItemSelected(Fragment.java:2830)
```

**Comment by federicoiosue** [comment]
Also reported [here](https://acra.omninotes.app/app/1/bug/116/report/541386d9-eeb2-4a56-aaf0-62e51895e194)
