### ISSUE TITLE
Missing backup folder in preferences implies NullPointerException

### ISSUE THREAD

**Issue by federicoiosue** [federicoiosue/Omni-Notes#916]
```
java.lang.NullPointerException: uriString
	at android.net.Uri$StringUri.<init>(Uri.java:475)
	at android.net.Uri$StringUri.<init>(Uri.java)
	at android.net.Uri.parse(Uri.java:437)
	at it.feio.android.omninotes.async.DataBackupIntentService.exportData(DataBackupIntentService.java:100)
	at it.feio.android.omninotes.async.DataBackupIntentService.onHandleIntent(DataBackupIntentService.java:79)
	at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:67)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:165)
	at android.os.HandlerThread.run(HandlerThread.java:61)
```

**Comment by federicoiosue** [comment]
This situation shouln't actually happen, its value should be checked elsewhere in the code before actually starting the backup process.
Check better (reminder to myself)
