### ISSUE TITLE
Crash on 6.2.8 during backup on Android 7

### ISSUE THREAD

**Issue by federicoiosue** [federicoiosue/Omni-Notes#925]
Bug report on Acrarium: [link](https://acra.omninotes.app/app/1/bug/479/report/3d456be3-ace9-443c-99ac-15ea0958b9bc)
```
java.lang.NullPointerException: uriString
	at android.net.Uri$StringUri.<init>(Uri.java:475)
	at android.net.Uri$StringUri.<init>(Uri.java)
	at android.net.Uri.parse(Uri.java:437)
	at it.feio.android.omninotes.async.DataBackupIntentService.exportData(DataBackupIntentService.java:100)
	at it.feio.android.omninotes.async.DataBackupIntentService.onHandleIntent(DataBackupIntentService.java:79)
	at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:67)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:165)
	at android.os.HandlerThread.run(HandlerThread.java:61)
```

**Comment by federicoiosue** [comment]
Seems to be due to hybrid management of storage. Try to move everything to the newer approach, this would also simplify the code
