### ISSUE TITLE
frequent crashes

### ISSUE THREAD

**Issue by gilcu3** [federicoiosue/Omni-Notes#990]
I am getting random frequent crashes while using the app. I am using the fdroid version on the latest Lineage OS (Android 15)

```
FATAL EXCEPTION: AsyncTask #12
Process: it.feio.android.omninotes.foss, PID: 10823
java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$4.done(AsyncTask.java:415)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:381)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:250)
	at java.util.concurrent.FutureTask.run(FutureTask.java:269)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.SecurityException: Caller it.feio.android.omninotes.foss needs to hold android.permission.SCHEDULE_EXACT_ALARM or android.permission.USE_EXACT_ALARM to set exact alarms.
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3183)
	at android.os.Parcel.createException(Parcel.java:3167)
	at android.os.Parcel.readException(Parcel.java:3150)
	at android.os.Parcel.readException(Parcel.java:3092)
	at android.app.IAlarmManager$Stub$Proxy.set(IAlarmManager.java:319)
	at android.app.AlarmManager.setImpl(AlarmManager.java:1084)
	at android.app.AlarmManager.setImpl(AlarmManager.java:1044)
	at android.app.AlarmManager.setExact(AlarmManager.java:808)
	at it.feio.android.omninotes.utils.ReminderHelper.addReminder(ReminderHelper.java:62)
	at it.feio.android.omninotes.utils.ReminderHelper.addReminder(ReminderHelper.java:51)
	at it.feio.android.omninotes.async.AlarmRestoreOnRebootService.onHandleWork(AlarmRestoreOnRebootService.java:60)
	at androidx.core.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:396)
	at androidx.core.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:387)
	at android.os.AsyncTask$3.call(AsyncTask.java:394)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	... 3 more
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.alarm.AlarmManagerService$4.set(AlarmManagerService.java:2964)
	at android.app.IAlarmManager$Stub.onTransact(IAlarmManager.java:189)
	at android.os.Binder.execTransactInternal(Binder.java:1500)
	at android.os.Binder.execTransact(Binder.java:1444)
```

**Comment by pratistha-05** [comment]
@gilcu3 are these crashes happening in android 14? seems like alarm permission is no longer granted by default in android 14. I think runtime check should be added

**Comment by gilcu3** [comment]
Indeed, it is android 14 :)

**Comment by federicoiosue** [comment]
@pratistha-05 great, you already worked on runtime permissions also.

**Comment by pratistha-05** [comment]
@gilcu3 can you tell me where exactly this issue is happening, so that i can replicate it

**Comment by gilcu3** [comment]
I think it was nowhere specific. I had the alarm permission off, and some notes with alarms set to the future. While reading other notes or creating new ones it would crash randomly.

**Comment by eren8204** [comment]
@gilcu3 should i start working on it
